version: '3.7'

services:
  app1:
    build: 
      context: .
      dockerfile: ./dockerfiles/dockerfile_1
    networks:
      my_network:
        ipv4_address: 172.168.2.5
    volumes:
      - ./webapp/hello1:/var/www/html
    ports:
      - "8081:80"
      - "2221:22"
  app2:
    build: 
      context: .
      dockerfile: ./dockerfiles/dockerfile_1
    networks:
      my_network:
        ipv4_address: 172.168.2.6
    volumes:
      - ./webapp/hello2:/var/www/html
    ports:
      - "8082:80"
      - "2222:22"
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.2.0/24
